apiVersion: v1beta1
creationTimestamp: null
items:
- apiVersion: v1beta1
  containerPort: 8080
  creationTimestamp: null
  id: simple-openshift-sinatra
  kind: Service
  port: 8080
  portName: simple-openshift-sinatra-sti-tcp-8080
  ports:
  - containerPort: 8080
    name: simple-openshift-sinatra-sti-tcp-8080
    port: 8080
    protocol: TCP
  protocol: TCP
  selector:
    deploymentconfig: simple-openshift-sinatra-sti
- apiVersion: v1beta1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1beta1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  parameters:
    output:
      to:
        name: simple-openshift-sinatra-sti
    source:
      git:
        uri: git://192.168.0.254/simple-openshift-sinatra-sti
      type: Git
    strategy:
      stiStrategy:
        builderImage: registry.access.redhat.com/openshift3_beta/ruby-20-rhel7
        clean: true
        image: registry.access.redhat.com/openshift3_beta/ruby-20-rhel7
      type: STI
  triggers:
  - github:
      secret: GpkYmPgw8HK_ICb3lVfz
    type: github
  - generic:
      secret: y3dS8QGAkbe1Y5Jq_wYf
    type: generic
- apiVersion: v1beta1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: simple-openshift-sinatra-sti
  template:
    controllerTemplate:
      podTemplate:
        desiredState:
          manifest:
            containers:
            - capabilities: {}
              image: library/simple-openshift-sinatra-sti:latest
              imagePullPolicy: ""
              name: simple-openshift-sinatra-sti
              ports:
              - containerPort: 8080
                name: simple-openshift-sinatra-sti-tcp-8080
                protocol: TCP
              resources: {}
            id: ""
            restartPolicy: {}
            version: v1beta2
            volumes: null
        labels:
          deploymentconfig: simple-openshift-sinatra-sti
      replicaSelector:
        deploymentconfig: simple-openshift-sinatra-sti
      replicas: 1
    strategy:
      type: Recreate
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - simple-openshift-sinatra-sti
      from:
        name: simple-openshift-sinatra-sti
      lastTriggeredImage: ""
      tag: latest
    type: ImageChange
kind: List
